language: python
sudo: required
python:
    - "2.7"
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
  - redis-server
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
before_script:
  - psql -U postgres -c "create extension postgis"
after_success:
    - coveralls
